# Generated by Django 5.2.10 on 2026-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_app_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
