# Generated by Django 5.2.10 on 2026-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_otp_alter_attachment_user_alter_folder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='sender_email',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
